name: emoji-lolachang
version: '0.3.0'
summary: emoji
description: Find relevant emoji from text on the command line.

grade: stable
confinement: strict

apps:
  emoji:
    command: bin/emoj
    plugs: [network]
    
parts:
  emoji:
    plugin: nodejs
    source: .
