name: emoji-lc
version: '0.3.0'
summary: emoji-lc
description: Find relevant emoji from text on the command line.

grade: stable
confinement: strict

apps:
  emoji-lc:
    command: bin/emoj
    plugs: [network]
    
parts:
  emoji-lc:
    plugin: nodejs
    source: .
